### ISSUE TITLE
add regression testing

### ISSUE THREAD

**Issue by Scrum** [GitScrum/slims#233]
https://github.com/DevExpress/testcafe

**Comment by miherlosev** [comment]
Hi
I am a developer from the [TestCafe](https://github.com/DevExpress/testcafe) team.
I can setup CI on `Travis` (real `Chrome` and `Firefox` browsers) and write a number of tests.
What do you think about it?

**Comment by Scrum** [comment]
Hi, it would be cool. How can I help ?

**Comment by miherlosev** [comment]
Need to decide what functionality should be tested.
At this moment, as I understand, we can test the following case on http://gitscrum.github.io/slims/:
- navigation between pages
- availability and correct dimentions of main elements on pages

Am I right or wrong?

**Comment by Scrum** [comment]
> Am I right or wrong?

I think so. 

> Need to decide what functionality should be tested.

What are the available opportunities ? Washes to be `EDGE` browser ? or `Safari` browser ? or mobile devices ? compare beetwin browser ? CI `Appveyor` ?

**Comment by miherlosev** [comment]
> What are the available opportunities ?

[Documentation](https://devexpress.github.io/testcafe/)


> Washes to be EDGE browser ? or Safari browser ? or mobile devices ? compare beetwin browser ?

[Browser support](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browser-support.html)

> CI Appveyor ?

[There is a command line interface](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html). So all CI systems are supported.

I propose to do the following:
- add integration with `appveyor` ci
- run tests in 4 latest browsers: `IE`, `Edge`, `Chrome`, `Firefox`

**Comment by Scrum** [comment]
> compare beetwin browser ?

supports ?

> I propose to do the following:
>
> - add integration with appveyor ci
> - run tests in 4 latest browsers: IE, Edge, Chrome, Firefox

I agree. 
Thanks for the links

**Comment by miherlosev** [comment]
> Hi, it would be cool. How can I help ?

I need a separate gulp task that correctly build and deploy github pages locally.
Now, then I run `deploy` gulp task it fail with message:
![Jekill fails](https://cloud.githubusercontent.com/assets/4133518/21798139/f669e6da-d723-11e6-8049-e535cbc597f5.png)

Trying to use `gulp-jekill` and `http-server` modules.

**Comment by Scrum** [comment]
You need to have locally installed `ruby` and `jekyll` pkg under ruby.

to run local server:
```bash
$ jekyll serve
```

access to the site will be 127.0.0.1:9001

or would you rather separate task to do ? In this case, I will try to do it quickly but you still need to install locally `ruby` and `jekyll`

let me know about your decision.

**Comment by miherlosev** [comment]
Ok.
I am continue working on this

**Comment by miherlosev** [comment]
Do you something about it?
![Problem](https://cloud.githubusercontent.com/assets/4133518/21804048/07bf5b62-d73e-11e6-9e04-7b18bbf0311d.png)

**Comment by Scrum** [comment]
Perhaps due to `ruby` version. I have `ruby 2.2.3p173 (2015-08-18 revision 51636)` or  `jekyll (2.5.3)` or `pygments.rb (0.6.3)`

**Comment by miherlosev** [comment]
Ok.
Now, I don't want to investigate this problem.
Can you create integration with `appveryour` as:
- install latest chrome and firefox version using choco
- build github pages and run jekill server
It should be a single gulp task.

When I will write tests and add appropriate code to the `appveyour.yml`.

**Comment by Scrum** [comment]
Ok. I have been in Lany to abandon the `jekyll` would be such a convenient build system and start the server ? [see](https://github.com/GitScrum/post-email/blob/master/package.json)

**Comment by miherlosev** [comment]
I don't know this.
Just I need a working local copy of http://gitscrum.github.io/slims/.

**Comment by Scrum** [comment]
ok, I will take time to migrate from `jekyll` to another system build and deployment of the local server.

**Comment by Scrum** [comment]
@miherlosev Hi, i created new branch milestone-0.5.1 where i migrated on new builder. You need follow contributing (to be in branch milestone-0.5.1) or:

1. you need clone slims
2. checkout milestone-0.5.1
3. npm install
4. npm run dev  *`should open a browser with the address localhost:3000 where you will see the start page`*

**Comment by Scrum** [comment]
@miherlosev If easier I can merge with the master and to endure the task in a separate issue ?

**Comment by miherlosev** [comment]
Merge with master, please.

**Comment by Scrum** [comment]
@miherlosev done

**Comment by miherlosev** [comment]
Tomorrow I will work on this

**Comment by Scrum** [comment]
related #251, #253
